blank_issues_enabled: false
contact_links:
  - name: Report provider bug
    url: https://github.com/recloudstream
    about: Please do not report any provider bugs here. This repository does not contain any providers. Please find the appropriate repository and report your issue there or join the discord.
  - name: Discord
    url: https://discord.gg/5Hus6fM
    about: Join our discord for faster support on smaller issues.
